# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20181219_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unit',
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
