# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20181219_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.ProductUnit'),
            preserve_default=False,
        ),
    ]
