# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0002_cooperativemember_collection_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemember',
            name='shares',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
