# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0003_cooperativemember_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativemember',
            name='collection_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cooperativemember',
            name='collection_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cooperativemember',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cooperativemember',
            name='shares',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
