# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20181219_0332'),
        ('coop', '0004_auto_20181218_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_reference', models.CharField(max_length=255)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(max_length=255)),
                ('order_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coop.CooperativeMember')),
            ],
            options={
                'db_table': 'member_order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coop.MemberOrder')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
    ]
