# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0005_memberorder_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberorder',
            name='accept_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberorder',
            name='collect_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberorder',
            name='delivery_accept_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberorder',
            name='delivery_reject_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberorder',
            name='reject_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberorder',
            name='ship_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberorder',
            name='order_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='memberorder',
            name='order_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='memberorder',
            name='status',
            field=models.CharField(default='PENDING', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='coop.MemberOrder'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
    ]
