# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0006_auto_20181219_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberorder',
            name='delivery_reject_reason',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='memberorder',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
