# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0007_auto_20181219_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperativemember',
            name='cotton_trees',
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='cotton_acreage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='soghum_acreage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='soya_beans_acreage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
