# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0001_initial'),
        ('coop', '0008_auto_20181220_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemember',
            name='parish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conf.Parish'),
        ),
        migrations.AlterField(
            model_name='cooperativemember',
            name='collection_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cooperativemember',
            name='collection_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cooperativemember',
            name='coop_role',
            field=models.CharField(choices=[('Chairperson', 'Chairperson'), ('Vice', 'Vice'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Committee Member', 'Committee Member'), ('Member', 'Member')], max_length=150),
        ),
        migrations.AlterField(
            model_name='cooperativemember',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cooperativemember',
            name='shares',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cooperativemember',
            name='village',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
