# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0009_auto_20190202_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperativemember',
            name='parish',
        ),
        migrations.AlterField(
            model_name='cooperativemember',
            name='coop_role',
            field=models.CharField(choices=[('Chairman', 'Chairman'), ('Vice Chairman', 'Vice Chairman'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary'), ('Member', 'Member'), ('Secretary Manager', 'Secretary Manager'), ('Patron', 'Patron')], max_length=150),
        ),
        migrations.AlterField(
            model_name='cooperativemember',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conf.Parish'),
        ),
    ]
