# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0001_initial'),
        ('coop', '0010_auto_20190202_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemember',
            name='parish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conf.Parish'),
        ),
        migrations.AlterField(
            model_name='cooperativemember',
            name='coop_role',
            field=models.CharField(choices=[('Chairman', 'Chairman'), ('Vice Chairman', 'Vice Chairman'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary'), ('Secretary Manager', 'Secretary Manager'), ('Patron', 'Patron'), ('Member', 'Member')], max_length=150),
        ),
        migrations.AlterField(
            model_name='cooperativemember',
            name='village',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
