# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-02 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0012_auto_20190202_0306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='non_member',
            new_name='name',
        ),
    ]
