# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-02 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0013_auto_20190202_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
