# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-03 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0014_collection_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='cooperative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coop.Cooperative'),
        ),
    ]
