# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-04 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0015_collection_cooperative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_date',
            field=models.DateField(),
        ),
    ]
