# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0017_auto_20190204_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativemember',
            name='coop_role',
            field=models.CharField(choices=[('Chairperson', 'Chairperson'), ('Vice', 'Vice'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary'), ('Committee Member', 'Committee Member'), ('Member', 'Member')], max_length=150),
        ),
    ]
