# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0018_auto_20190205_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativemember',
            name='collection_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AlterField(
            model_name='cooperativemember',
            name='collection_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32),
        ),
    ]
