# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0020_auto_20190205_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='collection',
            name='total_price',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='collection',
            name='unit_price',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
    ]
