# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0021_auto_20190205_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membertransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
        migrations.AlterField(
            model_name='membertransaction',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
    ]
