# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0022_auto_20190205_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membertransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
        migrations.AlterField(
            model_name='membertransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
        migrations.AlterField(
            model_name='membertransaction',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
    ]
