# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0023_auto_20190205_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberorder',
            name='cooperation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coop.Cooperative'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='collection',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='collection',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cooperativemember',
            name='collection_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AlterField(
            model_name='cooperativemember',
            name='collection_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32),
        ),
    ]
