# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0024_auto_20190206_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberorder',
            old_name='cooperation',
            new_name='cooperative',
        ),
    ]
