# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplates',
            name='collection',
            field=models.TextField(blank=True, null=True),
        ),
    ]
